apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: fips-chat
  labels:
    app: fips-chat
spec:
  output:
    to:
      kind: ImageStreamTag
      name: fips-chat:latest
  source:
    type: Git
    git:
      uri: https://github.com/wjackson/FIPS-Chat.git
    contextDir: /
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChange: {}