apiVersion: v1
kind: ServiceAccount
metadata:
  name: ollama-streamlit
  labels:
    app: ollama-streamlit
    app.kubernetes.io/name: ollama-streamlit
    app.kubernetes.io/component: web-ui
    app.kubernetes.io/part-of: ollama-platform
automountServiceAccountToken: false