apiVersion: v1
kind: Service
metadata:
  name: ollama-streamlit
  labels:
    app: ollama-streamlit
    app.kubernetes.io/name: ollama-streamlit
    app.kubernetes.io/component: web-ui
    app.kubernetes.io/part-of: ollama-platform
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: ollama-streamlit-tls
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: ollama-streamlit
  sessionAffinity: None